void initialize_seats();
void login_panel();
void admin_panel();
void customer_menu();
void save_movies();
void load_movies();
void save_bookings();
void load_bookings();
void add_movie();
void book_ticket(int movie_index);
void show_bill(Booking *booking);
void customer_view_bookings();
void admin_view_bookings();
void admin_view_movie_records();
void search_booking_by_id();
void payment_gateway(Booking *booking);
void generate_booking_id(Booking *booking);
void display_seat_availability(int movie_index);
bool book_seats(int movie_index, Booking *booking);
